version: '3'
services:
  v2ray-server:
    container_name: v2ray-server
    image: v2ray/official
    restart: always
    volumes:
      - ./v2ray-server.json:/etc/v2ray/config.json
  caddy:
    container_name: passwall-caddy
    image: abiosoft/caddy
    restart: always
    volumes:
      - ./caddy:/root/.caddy
      - ./Caddyfile:/etc/Caddyfile
    ports:
      - 80:80
    environment:
      - ACME_AGREE=true
      - DOMAIN=${DOMAIN}
      - MAIL=${MAIL}
    links:
      - v2ray-server
  trojan-server:
    image: trojangfw/trojan
    container_name: trojan-server
    restart: always
    ports:
      - 443:443
    environment:
      - DOMAIN=${DOMAIN}
    volumes:
      - ./trojan-server.json:/config/config_template.json
      - ./caddy/acme/acme-v02.api.letsencrypt.org/sites:/sites
    command: >-
      /bin/ash -c "cp config_template.json config.json &&
        sed -e "s@CERT_PATH@/sites/${DOMAIN}/${DOMAIN}.crt@g" -i config.json &&
        sed -e "s@KEY_PATH@/sites/${DOMAIN}/${DOMAIN}.key@g" -i config.json &&
        exec trojan config.json"
    links:
      - caddy:__DOCKER_CADDY__
